# Generated by Django 3.1.1 on 2020-10-05 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_democashaccount_realcashaccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='chosen_account',
            field=models.CharField(choices=[('Demo', 'Demo'), ('Real', 'Real')], default=('Demo', 'Demo'), max_length=10),
        ),
        migrations.AlterField(
            model_name='democashaccount',
            name='profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='demo_account', to='accounts.profile'),
        ),
        migrations.AlterField(
            model_name='realcashaccount',
            name='profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='real_account', to='accounts.profile'),
        ),
    ]
