# Generated by Django 3.1.1 on 2020-10-06 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20201005_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='democashaccount',
            name='havings',
            field=models.DecimalField(decimal_places=2, default=1000, max_digits=10),
        ),
        migrations.AlterField(
            model_name='profile',
            name='chosen_account',
            field=models.CharField(choices=[('Demo', 'Demo'), ('Real', 'Real')], default=('Demo', 'Demo'), max_length=20),
        ),
        migrations.AlterField(
            model_name='realcashaccount',
            name='havings',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
