# Generated by Django 3.1.1 on 2020-10-09 15:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Commodity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('mean_price', models.DecimalField(decimal_places=2, default=10, max_digits=10)),
                ('price', models.DecimalField(decimal_places=2, default=10, max_digits=10)),
            ],
            options={
                'verbose_name_plural': 'commodities',
            },
        ),
        migrations.CreateModel(
            name='HistoricalCommodity',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('mean_price', models.DecimalField(decimal_places=2, default=10, max_digits=10)),
                ('price', models.DecimalField(decimal_places=2, default=10, max_digits=10)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical commodity',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Bet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_real_account', models.BooleanField(choices=[(True, 'yes'), (False, 'no')], default=False, null=True)),
                ('direction', models.BooleanField(choices=[(True, 'up'), (False, 'down')], null=True)),
                ('venture', models.DecimalField(choices=[(1, '1'), (2, '2'), (5, '5'), (10, '10'), (20, '20'), (50, '50'), (100, '100')], decimal_places=2, max_digits=10)),
                ('duration', models.IntegerField(choices=[(10, '10'), (30, '30'), (60, '60'), (120, '120')])),
                ('time_start', models.TimeField(auto_now_add=True)),
                ('commodity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trading.commodity')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.profile')),
            ],
        ),
    ]
