# Generated by Django 3.1.1 on 2020-10-16 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bet',
            name='price_when_created',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
