# Generated by Django 3.1.1 on 2020-10-16 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bet',
            name='success',
            field=models.IntegerField(blank=True, choices=[(1, 'Won'), (0, 'Equal'), (-1, 'Lost')], null=True),
        ),
    ]
