# Generated by Django 3.1.1 on 2020-10-12 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0002_auto_20201012_1853'),
    ]

    operations = [
        migrations.AddField(
            model_name='bet',
            name='income',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
