# Generated by Django 3.1.1 on 2020-10-12 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0003_bet_income'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bet',
            name='income',
        ),
        migrations.AddField(
            model_name='bet',
            name='success',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
